services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./config/credentials.json:/google-credentials.json:ro
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.data/db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8080"