package com.mrkirby153.foodandfriends.entity

import org.springframework.data.jpa.repository.JpaRepository
import javax.persistence.Entity
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table

@Entity
@Table(name = "attendee")
class Attendee(
    var user: String? = null,
    @ManyToOne
    @JoinColumn(name = "event_id")
    var event: Event? = null
) : AbstractAutogeneratedJpaEntity<Long>()

interface AttendeeRepo : JpaRepository<Attendee, Long> {

    fun findFirstByEventAndUser(event: Event, user: String?): Attendee?

    fun findAllByEvent(event: Event): List<Attendee>
}