package com.mrkirby153.foodandfriends.entity

import org.springframework.data.jpa.repository.JpaRepository
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Table

@Entity
@Table(name = "emails")
class Email(
    @Column(name = "user_id")
    var userId: String? = null,

    @Column(name = "email")
    var email: String? = null
) : AbstractAutogeneratedJpaEntity<Long>()

interface EmailRepo : JpaRepository<Long, Email>