package com.mrkirby153.foodandfriends.entity

import org.springframework.data.jpa.repository.JpaRepository
import java.sql.Timestamp
import javax.persistence.CascadeType
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.OneToMany
import javax.persistence.Table

@Entity
@Table(name = "event")
class Event(
    /**
     * The date that the event occurs on
     */
    var date: Timestamp? = null,
    /**
     * The owner of the event
     */
    var owner: String? = null,

    /**
     * The identifier of the attending button to mark participation
     */
    @Column(name = "attending_button") var attendingButton: String? = null,

    @OneToMany(mappedBy = "event", cascade = [CascadeType.REMOVE], orphanRemoval = true)
    var attendees: MutableSet<Attendee> = mutableSetOf()
) : AbstractAutogeneratedJpaEntity<Long>()

interface EventRepo : JpaRepository<Long, Event>